export const ALL_PROPERTY_REQUEST = "ALL_PROPERTY_REQUEST";
export const ALL_PROPERTY_SUCCESS = "ALL_PROPERTY_SUCCESS";
export const ALL_PROPERTY_FAIL = "ALL_PROPERTY_FAIL";

export const NEW_PROPERTY_REQUEST = "NEW_PROPERTY_REQUEST";
export const NEW_PROPERTY_SUCCESS = "NEW_PROPERTY_SUCCESS";
export const NEW_PROPERTY_RESET = "NEW_PROPERTY_RESET";
export const NEW_PROPERTY_FAIL = "NEW_PROPERTY_FAIL";

export const PROPERTY_DETAILS_REQUEST = "PROPERTY_DETAILS_REQUEST";
export const PROPERTY_DETAILS_SUCCESS = "PROPERTY_DETAILS_SUCCESS";
export const PROPERTY_DETAILS_FAIL = "PROPERTY_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";